[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "probe-run --chip cortex-m33"
rustflags = [
    "-C", "link-arg=--nmagic",
    "-C", "link-arg=-Tlink.x",
]

[build]
target = "thumbv8m.main-none-eabi" # Cortex-M33 (without FPU)
